import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Provider } from "./components/Web3Provider";
import { Typography } from "@mui/material";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "./components/ConnectButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Web3Provider>
        <body className={inter.className}>
          <header className={styles.header}>
            <Typography variant="h4" component="h1" className={styles.title}>
              FHE Swap
            </Typography>
            <div>
              <ConnectButton />
            </div>
          </header>
          {children}
        </body>
      </Web3Provider>
    </html>
  );
}
